"""Alter Building Table

Revision ID: 5b9616d3e3be
Revises: 1fb1f306b51a
Create Date: 2025-02-10 00:59:36.277176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "5b9616d3e3be"
down_revision: Union[str, None] = "1fb1f306b51a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "buildings",
        "location",
        existing_type=Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        type_=Geography(
            geometry_type="POINT",
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "buildings",
        "location",
        existing_type=Geography(
            geometry_type="POINT",
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        type_=Geometry(
            geometry_type="POINT",
            from_text="ST_GeomFromEWKT",
            name="geometry",
            nullable=False,
            _spatial_index_reflected=True,
        ),
        existing_nullable=False,
    )
    op.create_table(
        "layer",
        sa.Column(
            "topology_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "layer_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "schema_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "table_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "feature_column", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "feature_type", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "level",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "child_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["topology_id"], ["topology.id"], name="layer_topology_id_fkey"
        ),
        sa.PrimaryKeyConstraint("topology_id", "layer_id", name="layer_pkey"),
        sa.UniqueConstraint(
            "schema_name",
            "table_name",
            "feature_column",
            name="layer_schema_name_table_name_feature_column_key",
        ),
    )
    op.create_table(
        "topology",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "precision",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "hasz",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="topology_pkey"),
        sa.UniqueConstraint("name", name="topology_name_key"),
    )
    # ### end Alembic commands ###
