"""Alter Activity table

Revision ID: 7b5d400b904a
Revises: 275520a01bcf
Create Date: 2025-02-09 23:09:25.686355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "7b5d400b904a"
down_revision: Union[str, None] = "275520a01bcf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ...
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topology",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('topology_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "precision",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "hasz",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="topology_pkey"),
        sa.UniqueConstraint("name", name="topology_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "layer",
        sa.Column(
            "topology_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "layer_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "schema_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "table_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "feature_column", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "feature_type", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "level",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "child_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["topology_id"], ["topology.id"], name="layer_topology_id_fkey"
        ),
        sa.PrimaryKeyConstraint("topology_id", "layer_id", name="layer_pkey"),
        sa.UniqueConstraint(
            "schema_name",
            "table_name",
            "feature_column",
            name="layer_schema_name_table_name_feature_column_key",
        ),
    )
    # ### end Alembic commands ###
