"""Create tables

Revision ID: fed0cd37a340
Revises:
Create Date: 2025-02-09 22:50:51.866760

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "fed0cd37a340"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "level",
            sa.Enum("LEVEL_1", "LEVEL_2", "LEVEL_3", name="activitylevel"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["activities.id"],
            name=op.f("fk_activities_parent_id_activities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
        sa.UniqueConstraint("name", name=op.f("uq_activities_name")),
    )
    op.create_table(
        "buildings",
        sa.Column("address", sa.String(), nullable=False),
        sa.Column(
            "location",
            Geometry(
                geometry_type="POINT",
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
        sa.UniqueConstraint("address", name=op.f("uq_buildings_address")),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name=op.f("fk_organizations_activity_id_activities"),
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_organizations_building_id_buildings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topology",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('topology_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "precision",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "hasz",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="topology_pkey"),
        sa.UniqueConstraint("name", name="topology_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "layer",
        sa.Column(
            "topology_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "layer_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "schema_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "table_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "feature_column", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "feature_type", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "level",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "child_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["topology_id"], ["topology.id"], name="layer_topology_id_fkey"
        ),
        sa.PrimaryKeyConstraint("topology_id", "layer_id", name="layer_pkey"),
        sa.UniqueConstraint(
            "schema_name",
            "table_name",
            "feature_column",
            name="layer_schema_name_table_name_feature_column_key",
        ),
    )
    op.drop_table("organizations")
    op.drop_table("buildings")
    op.drop_table("activities")
    # ### end Alembic commands ###
